# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://phptownhall.com
title: PHP Town Hall
subtitle: Ben, Phil and a super-star guest answer questions and talk about current events in the PHP world.
author: Ben Edmunds &amp; Phil Sturgeon
description: Town Hall is a way for PHP developers to raise questions about current events (or upcoming things) in the PHP community, with different guests each week.

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /itunes.rss
subscribe_email:
# RSS feeds can list your email address if you like
email: me@philsturgeon.uk

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: /
permalink: /:title/

# Build settings
markdown: kramdown
highlighter: pygments # default python pygments have been replaced by pygments.rb
gems:
  - jekyll-paginate

paginate: 25
paginate_path: "archive/:num"

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Twitter
twitter_username: phptownhall

# Google Analytics
google_analytics_tracking_id: UA-37199526-1

# Google Plus
google_plus_username: PHPTownHall
